version: "3.4"

services:
  coinbase:
    container_name: coinbase
    image: ghcr.io/volkovlabs/crypto-app:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    command: ["node", "dist/coinbase.js"]
    env_file:
      - ./coinbase.env

  tickers:
    container_name: tickers
    image: ghcr.io/volkovlabs/crypto-app:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    command: ["node", "dist/tickers.js"]
    env_file:
      - ./coinbase.env

  redis:
    container_name: redis
    image: ghcr.io/redisgrafana/redis-prophet:latest
    ports:
      - 6379:6379

  grafana:
    container_name: grafana
    image: ghcr.io/redisgrafana/redis-app:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=light
    volumes:
      - ./provisioning:/etc/grafana/provisioning
